"""added repr for both classes and added  random roles

Revision ID: 0a5211a031d7
Revises: 1f6d7461e6ae
Create Date: 2023-06-27 17:20:51.302576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5211a031d7'
down_revision = '1f6d7461e6ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_auditions_role_id_auditions', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_auditions_role_id_roles'), 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_auditions_role_id_roles'), type_='foreignkey')
        batch_op.create_foreign_key('fk_auditions_role_id_auditions', 'auditions', ['role_id'], ['id'])

    # ### end Alembic commands ###
