"""added seed file

Revision ID: 1f6d7461e6ae
Revises: 992a514192a1
Create Date: 2023-06-27 16:08:58.652829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6d7461e6ae'
down_revision = '992a514192a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
