"""corrected relationship btwn audition and role

Revision ID: 992a514192a1
Revises: 65b900e519db
Create Date: 2023-06-27 16:00:12.553289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992a514192a1'
down_revision = '65b900e519db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_auditions_role_id_auditions'), 'auditions', ['role_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_roles_audition_id_auditions', type_='foreignkey')
        batch_op.drop_column('audition_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audition_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_roles_audition_id_auditions', 'auditions', ['audition_id'], ['id'])

    with op.batch_alter_table('auditions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_auditions_role_id_auditions'), type_='foreignkey')

    # ### end Alembic commands ###
