"""added lead and understudy method for Role class

Revision ID: c850a9b679b0
Revises: 0a5211a031d7
Create Date: 2023-06-27 20:54:47.478437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c850a9b679b0'
down_revision = '0a5211a031d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
